In [1]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    849     72   John
1  2023-01-02       B   West    824     14   Mary
2  2023-01-03       C  North    526     43    Bob
3  2023-01-04       D  South    840     58  Alice
4  2023-01-05       A   East    568     70   John
5  2023-01-06       B   West    836     64   Mary
6  2023-01-07       C  North    983     94    Bob
7  2023-01-08       D  South    811     51  Alice
8  2023-01-09       A   East    476     69   John
9  2023-01-10       B   West    285     17   Mary
10 2023-01-11       C  North    426     76    Bob
11 2023-01-12       D  South    624     69  Alice
12 2023-01-13       A   East    633     54   John
13 2023-01-14       B   West    297     70   Mary
14 2023-01-15       C  North    642     53    Bob
15 2023-01-16       D  South    601     93  Alice
16 2023-01-17       A   East    276     62   John
17 2023-01-18       B   West    210     70   Mary
18 2023-01-19       C  North    157     68    Bob
19 2023-01-20       D  South    877     21  Alice

In [5]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')  ## mean fill krta hai

Product      A      B      C      D
Region
East     560.4    NaN    NaN    NaN
North      NaN    NaN  546.8    NaN
South      NaN    NaN    NaN  750.6
West       NaN  490.4    NaN    NaN

In [6]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     568.0    NaN    NaN    NaN
North      NaN    NaN  526.0    NaN
South      NaN    NaN    NaN  811.0
West       NaN  297.0    NaN    NaN

In [8]:
pivot2=pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     560.4    NaN    NaN    NaN  65.4   NaN   NaN   NaN
North      NaN    NaN  546.8    NaN   NaN   NaN  66.8   NaN
South      NaN    NaN    NaN  750.6   NaN   NaN   NaN  58.4
West       NaN  490.4    NaN    NaN   NaN  47.0   NaN   NaN

    Cross Tab

In [10]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0